### PR TITLE
Add Fluidsynth without glib dependency

### PR DESCRIPTION
**Pull request by Ghabry**
marked as WIP because this needs compile tests and runtime tests, this is experimental

### CODE REVIEW

**Comment by Ghabry** [comment]
@krmbn0576 

Warning: We have not tested this PR yet on Emscripten

When you use the latest Player and this version of the buildscripts it should fix the MIDI related issues that were reported e.g. in this twitter thread https://twitter.com/EasyRPG/status/1415728050453549057

The Player fixed the looping and this PR here fixes the wrong drums.

There can be still bugs left but it will be better than before ;)

**Comment by krmbn0576** [comment]
Hmm I tested this branch, but it still doesn't fix the Shop 3.mid drum... 🤔

**Comment by Ghabry** [comment]
Strange 🤔

Try with a clean build folder (Delete lib and include).

Otherwise cmake will find fluidlite 🙈

**Comment by krmbn0576** [comment]
```
-- Found the following ICU libraries:
--   i18n (required)
--   uc (required)
--   data (required)
-- Found ICU: /mnt/c/Users/nozomi_ikuyama/Documents/EasyRPG/buildscripts/emscripten/include
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- This means no API documentation is generated.
-- Found ZLIB: /mnt/c/Users/nozomi_ikuyama/Documents/EasyRPG/buildscripts/emscripten/lib/libz.a
-- Found PNG: /mnt/c/Users/nozomi_ikuyama/Documents/EasyRPG/buildscripts/emscripten/lib/libpng.a
-- Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
-- Could NOT find WildMidi (missing: WILDMIDI_LIBRARY WILDMIDI_INCLUDE_DIR)
-- Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARY FLUIDSYNTH_INCLUDE_DIR)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
--
-- Target system: SDL2
--
-- liblcf: Built from https://github.com/EasyRPG/liblcf.git
--
-- Audio backend: SDL2
--
-- WAV playback: built-in (dr_wav);libsndfile
-- MIDI playback: FluidLite;built-in (FmMidi)
-- MP3 playback: mpg123
-- Ogg Vorbis playback: libvorbis
-- MOD playback: libxmp
-- Opus playback: opusfile
-- Resampler: speexdsp
--
-- Font rendering: built-in
--
-- Manual page: Unavailable
-- Bash completion: Available
-- Doxygen: Unavailable
--
-- Configuring done
```

fluidlite used. 😭

**Comment by Ghabry** [comment]
Did you use my branch of the buildscripts? (Ghabry/easyrpg-buildscripts branch fluidsynth)

If yes: Strange o_O. Try deleting CMakeCache.txt and CMakeFiles to make CMake search again.

**Comment by krmbn0576** [comment]
I used `Ghabry:fluidsynth` branch and deleted 

```
```

**Comment by Ghabry** [comment]
I used the following CMake line and it worked for me:

All this ugly ``FIND_ROOT_PATH`` stuff is needed because otherwise it will not find the libraries :(

```
emcmake cmake . -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH \
 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
 -DCMAKE_PREFIX_PATH=$PWD/.. -DCMAKE_BUILD_TYPE=Release -DPLAYER_JS_BUILD_SHELL=ON \
 -DPLAYER_JS_OUTPUT_NAME=index -DPLAYER_BUILD_LIBLCF=ON -DLIBLCF_WITH_XML=OFF \
 -DLIBLCF_ENABLE_TOOLS=OFF
```

You only have to adjust ``CMAKE_PREFIX_PATH`` to the emscripten buildscript folder 

```
configure: cmake . -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH -DCMAKE_PREFIX_PATH=/home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/player/.. -DCMAKE_BUILD_TYPE=Release -DPLAYER_JS_BUILD_SHELL=ON -DPLAYER_JS_OUTPUT_NAME=index -DPLAYER_BUILD_LIBLCF=ON -DLIBLCF_WITH_XML=OFF -DLIBLCF_ENABLE_TOOLS=OFF -DCMAKE_TOOLCHAIN_FILE=/usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/node
-- Found SDL2: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libSDL2.a (Required is at least version "2.0.5") 
-- Found Git: /usr/bin/git (found version "2.32.0") 
Clonando en '/home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/player/lib/liblcf'...
-- Found the following ICU libraries:
--   i18n (required)
--   uc (required)
--   data (required)
-- Found ICU: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/include (found version "69.1") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- This means no API documentation is generated.
-- Found ZLIB: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libz.a (found version "1.2.11") 
-- Found PNG: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libpng.a (found version "1.6.37") 
-- Found Pixman: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libpixman-1.a  
-- Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS) 
-- Could NOT find ALSA (missing: ALSA_INCLUDE_DIR) 
-- Found speexdsp: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libspeexdsp.a  
-- Found mpg123: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libmpg123.a  
-- Found LibSndFile: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libsndfile.a  
-- Found Vorbisfile: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libvorbisfile.a  
-- Found Opusfile: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libopusfile.a  
-- Could NOT find WildMidi (missing: WILDMIDI_INCLUDE_DIR) 
-- Found FluidSynth: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/lib/libfluidsynth.a  
-- Found XMP: /lib/libxmp.so  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- 
-- Target system: SDL2
-- 
-- liblcf: Built from https://github.com/EasyRPG/liblcf.git
-- 
-- Audio backend: SDL2
-- 
-- WAV playback: built-in (dr_wav);libsndfile
-- MIDI playback: FluidSynth;built-in (FmMidi)
-- MP3 playback: mpg123
-- Ogg Vorbis playback: libvorbis
-- MOD playback: libxmp
-- Opus playback: opusfile
-- Resampler: speexdsp
-- 
-- Font rendering: built-in
-- 
-- Manual page: Generated
-- Bash completion: Available
-- Doxygen: Unavailable
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gabriel/Programmierung/easyrpg/easyrpg-buildscripts/emscripten/player
```

**Comment by krmbn0576** [comment]
```
$ echo $PATH_TO_BUILDSCRIPTS
/mnt/c/Users/-/Documents/EasyRPG/buildscripts

$ cmake . -GNinja -Bembuild -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH -DPLAYER_BUILD_LIBLCF=ON -DLIBLCF_WITH_XML=OFF -DLIBLCF_ENABLE_TOOLS=OFF -DCMAKE_TOOLCHAIN_FILE=$PATH_TO_BUILDSCRIPTS/emscripten/emsdk-portable/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_PREFIX_PATH=$PATH_TO_BUILDSCRIPTS/emscripten -DCMAKE_BUILD_TYPE=Release -DPLAYER_JS_BUILD_SHELL=ON -DPLAYER_JS_OUTPUT_NAME=index -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR) (Required is
  at least version "2.0.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  builds/cmake/Modules/FindSDL2.cmake:152 (find_package_handle_standard_args)
  CMakeLists.txt:473 (find_package)

-- Configuring incomplete, errors occurred!
```

I'm doing an emscripten build, so the commands are a little different, but they are as you describe. But it doesn't work 🤔

**Comment by Ghabry** [comment]
This looks right so I am a bit clueless where the problem is.

Delete "embuild" folder and try again, I am a bit out of ideas right now :(

**Comment by krmbn0576** [comment]
`git clean -xdf` and then rerun 0_build_everything.sh, and libfluidsynth.a was generated successfully.
However, I get the following Ninja error

```
$ cmake . -GNinja -Bembuild -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH -DPLAYER_BUILD_LIBLCF=ON -DLIBLCF_WITH_XML=OFF -DLIBLCF_ENABLE_TOOLS=OFF -DCMAKE_TOOLCHAIN_FILE=$PATH_TO_BUILDSCRIPTS/emscripten/emsdk-portable/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_PREFIX_PATH=$PATH_TO_BUILDSCRIPTS/emscripten -DCMAKE_BUILD_TYPE=Release -DPLAYER_JS_BUILD_SHELL=ON -DPLAYER_JS_OUTPUT_NAME=index -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file:
  /mnt/c/Users/-/Documents/EasyRPG/buildscripts/emscripten/emscripten/emsdk-portable/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by Ghabry** [comment]
Did you install a local version of emscripten in the meanwhile?
If yes the buildscripts skip by now the emscripten sdk install.

You can figure this out by running "emcc". If it gives you "No input files" emscripten is installed locally.

In that case you can omit the ``-DCMAKE_TOOLCHAIN_FILE`` option and write ``emcmake`` at the beginning of the command (before ``cmake``).

**Comment by krmbn0576** [comment]
```
$ emcc

Command 'emcc' not found, but can be installed with:

sudo apt install emscripten
```

No Emscripten 🤔 maybe...

**Comment by Ghabry** [comment]
```
/mnt/c/Users/-/Documents/EasyRPG/buildscripts/emscripten/emscripten/emsdk-portable/upstream/
```

The first "emscripten" looks duplicated, should be ``buildscripts/emscripten/emsdk-portable`` I guess?

**Comment by krmbn0576** [comment]
>The first "emscripten" looks duplicated

Oh cannot `0_build_everything.sh` be run multiple times? Is there any way to clean it up?

**Comment by krmbn0576** [comment]
Yeah, I totally get it! The absolute path emscripten directory is being repeated twice! `/emscripten/emscripten/` I corrected it and it worked. Thanks very much 😇 

Benefits:
`Shop 3.mid` drums are now completely fixed!

Regression:
I hear a noise when changing the bgm...

**Comment by Ghabry** [comment]
Great. Thanks for confirming that Fluidsynth is the way to go.

Now only have to figure out where this noise is coming from...

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Was confirmed to work on multiple platforms - I'm done with this.

**Comment by Ghabry** [comment]
This fails the build on macOS... Some linker issue I missed. Will patch this :/

Also switch is broken because it uses a makefile with hardcoded dependencies but carstene1ns' CMake migration is almost finished, so no real need to fix this anymore 😁

**Comment by Ghabry** [comment]
The linker issue is caused by ``CMAKE_SYSTEM_NAME=Generic``. Maybe this option shouldn't be hardcoded

**Pull request merged**
