### PR TITLE
Wildmidi for Wii and Android buildfix

### PR DESCRIPTION
**Pull request by carstene1ns**
Wii: WildMidi and expat added, scripts polished and cleaned up, some libraries updated (more details in the commit message).
Android: Build fixed, when no `ccache` is available (aborted due to `set -e`), noticed by @Ghabry on IRC.

### CODE REVIEW

**Comment by carstene1ns** [comment]
Player change to build for Wii: https://paste.xinu.at/gVMYS/

**Comment by carstene1ns** [comment]
It seems like the Wii port now constantly crashes or locks up during music play.
No idea if it is because of this or EasyRPG/Player#1000, but at least for one case I have inspected the stack dump:
wii_crash

**Comment by Ghabry** [comment]
woah that is an awesome stackdump. How did you get it. I had this speexdsp destructor crash in fastwav when "open" failed. But not sure if its the fault of fastwav. Looks more like a problem in speexdsp destructor in error case

I think you can at least prevent the crash in audio_resampler by initializing "conversion_state" to nullptr, the variable is not initialized when Open fails and  frees garbage :/

**Comment by carstene1ns** [comment]
I have changed the audio_resampler now (is it even valid to use 0 to check for NULL pointers?): https://paste.xinu.at/Gs31p/
However, the crash is still there.

**Comment by carstene1ns** [comment]
Question: Do we want to keep the fallback to SDL_mixer's music code for now? I have disabled Timidity, MikMod and Ogg/Vorbis playback in this PR. This means currently there is no MOD support on Wii (until i add the xmp_decoder).

**Comment by Ghabry** [comment]
Keep it disabled, nobody will miss MOD soon.

**Pull request merged**
