### PR TITLE
Migrate to vcpkg

### LINKED ISSUE #24: Migrate to "vcpkg" tool for windows toolchain
vcpkg tool appears to be under development since this year and is a tool+repo by Microsoft which contains user contributed buildscripts for some libraries: https://github.com/Microsoft/vcpkg

Have to check if it supports static library builds.

So this basicly fulfills the same purpose as my powershell script but is written in CMake. :D. Does not ship all libraries (and for ICU we better build the small data file on our own).

### PR DESCRIPTION
**Pull request by Ghabry**
Fix #24 

This will break our infrastructure.

The vcpkg is completely vanilla except for our custom ICU. You could use the vcpkg ICU but the only difference here is the executable size (20 MB smaller).

### CODE REVIEW

**Comment by Ghabry** [comment]
sometimes the build gets stuck but I guess that's a problem with the terminal we don't really have control about...

**Comment by Ghabry** [comment]
A good time for merging this is Friday. Then I have the whole evening to fix Jenkins.

**Comment by Ghabry** [comment]
New merge window: Wednesday 6 PM or Sunday 6 PM, next Friday is very bad timewise for me.

Will fix Editor, Player and Tools after this PR is merged, is only Jenkins work.

**Comment by Ghabry** [comment]
The Editor builds similiar to Player, just need to add Qt to the prefix path:
```
cmake . -GNinja -DSHARED_RUNTIME=OFF -DVCPKG_TARGET_TRIPLET=x86-windows-static^
  -DCMAKE_TOOLCHAIN_FILE="%EASYDEV_VCPKG%\scripts\buildsystems\vcpkg.cmake"^
  -DBUILD_SHARED_LIBS=OFF^
  -DCMAKE_INSTALL_PREFIX="%CD%\build" -DCMAKE_BUILD_TYPE=RelWithDebInfo^
  -DCMAKE_PREFIX_PATH="%WORKSPACE%\..\liblcf-win64\build;%QT_DIR%"
```

**Comment by carstene1ns** [comment]
Okay, it does not. So maybe checking for `vcpkg.exe` would be good.

**Pull request merged**
