### PR TITLE
Remove obsolete Windows libs and update other ones

### PR DESCRIPTION
**Pull request by carstene1ns**

### CODE REVIEW

**Comment by Ghabry** [comment]
I'm continuing with this in my branch, will push to that PR-branch when ready: https://github.com/Ghabry/easyrpg-buildscripts/commits/msvc

Good news: ICU is now UWP compatible and libsndfile doesn't use GNU extensions (dynamic arrays) anymore 👍

**Comment by carstene1ns** [comment]
Thanks for picking up my branch, Ghabry.
Do you intend to add a patch for WildMidi to allow using it on Windows later?
We can leave this stay open then.

**Comment by Ghabry** [comment]
I will be lazy and provide a patch that explicitly uses the ANSI Api under Windows. I don't think that it's important to have full unicode support for the wildmidi.cfg & instrument path.

**Comment by Ghabry** [comment]
Just noticed that the exe is still 30 MB in size... Probably still not using our data file >.<  Well, hopefully an easy fix.

**Comment by carstene1ns** [comment]
Just a random guess: We are building ICU 59 now. However the datafile is for ICU 58 (named `icudt58l.dat`).
Btw. we forgot to remove `libmodplug`, should not be needed anymore. I did not initially remove it, because there was no xmp build at this time.

**Comment by Ghabry** [comment]
Yeah, thats the reason 👍

**Comment by carstene1ns** [comment]
I have updated the ICU data package now. It includes the data file for 56, 58 and 59 now.
So, just rebuilding the toolchain should be enough to make this work.

**Pull request merged**
