### PR TITLE
Do not copy ICU for cross build

### PR DESCRIPTION
**Pull request by carstene1ns**
Just build in separate dirs.
This has the additional benefit that it fixes the WiiU problem... :^)

One caveat: The applied platform patches must be written in a way the native build is not broken.
The forced data install is untested. Just did a test run for WiiU.

Additionally cleans up a bit and allows ccache for native ICU.

Some 3DS type fixes as usual...

### CODE REVIEW

**Comment by carstene1ns** [comment]
This sometimes uses our custom data file and sometimes not. Needs investigating...

**Comment by Ghabry** [comment]
About Android: libpng uses some generator scripts and our compiler is ``clang -target ...``. CMake splits this in two variables and the generator script ignores the second which is some ``CMAKE_C_COMPILER_ARG1``.

Possible solution (move the ``-target`` into ``CFLAGS`` instead).

```diff
diff --git a/android/2_build_toolchain.sh b/android/2_build_toolchain.sh
index f965495..dcadfc7 100755
--- a/android/2_build_toolchain.sh
+++ b/android/2_build_toolchain.sh
@@ -65,6 +65,7 @@ function build() {
 
 	echo "Preparing $1 toolchain"
 
+	export TARGET_HOST="$4"
 	export TARGET_API=16
 	if [ "$3" = "arm64" ]; then
 		# Minimum API 21 on ARM64
@@ -84,15 +85,14 @@ function build() {
 	export NM=$NDK_PATH/llvm-nm
 	export RANLIB=$NDK_PATH/llvm-ranlib
 
-	export CFLAGS="-no-integrated-as -g0 -O2 -fPIC $5"
+	export CFLAGS="-target ${TARGET_HOST}${TARGET_API} -no-integrated-as -g0 -O2 -fPIC $5"
 	export CXXFLAGS="$CFLAGS"
 	export CPPFLAGS="-I$PLATFORM_PREFIX/include -I$NDK_ROOT/sources/android/cpufeatures"
 	export LDFLAGS="-L$PLATFORM_PREFIX/lib"
 	unset PKG_CONFIG_PATH
 	export PKG_CONFIG_LIBDIR=$PLATFORM_PREFIX/lib/pkgconfig
-	export TARGET_HOST="$4"
-	export CC="clang -target ${TARGET_HOST}${TARGET_API}"
-	export CXX="clang++ -target ${TARGET_HOST}${TARGET_API}"
+	export CC="clang"
+	export CXX="clang++"
 
 	mkdir -p $PLATFORM_PREFIX
 	make_meson_cross "${TARGET_HOST}${TARGET_API}" > $PLATFORM_PREFIX/meson-cross.txt

```

**Comment by Ghabry** [comment]
This one is better:

```diff
diff -Naur libpng-1.6.39-orig/scripts/genout.cmake.in libpng-1.6.39/scripts/genout.cmake.in
--- libpng-1.6.39-orig/scripts/genout.cmake.in	2022-11-20 22:53:23.000000000 +0100
+++ libpng-1.6.39/scripts/genout.cmake.in	2024-06-09 18:38:38.953706845 +0200
@@ -14,6 +14,7 @@
 
 set(AWK "@AWK@")
 set(CMAKE_C_COMPILER "@CMAKE_C_COMPILER@")
+set(CMAKE_C_COMPILER_ARG1 @CMAKE_C_COMPILER_ARG1@)
 set(CMAKE_C_FLAGS @CMAKE_C_FLAGS@)
 set(INCDIR "@CMAKE_CURRENT_BINARY_DIR@")
 set(PNG_PREFIX "@PNG_PREFIX@")
@@ -58,7 +59,7 @@
     set(PNG_PREFIX_DEF "-DPNG_PREFIX=${PNG_PREFIX}")
   endif()
 
-  execute_process(COMMAND "${CMAKE_C_COMPILER}" "-E"
+  execute_process(COMMAND "${CMAKE_C_COMPILER}" ${CMAKE_C_COMPILER_ARG1} "-E"
                           ${CMAKE_C_FLAGS}
                           ${PLATFORM_C_FLAGS}
                           "-I${SRCDIR}"
```

**Comment by carstene1ns** [comment]
Yeah, also found out about this `ARG1` stuff and the other possible solution was to use a compiler driver script for cmake, but this would just contain "exec $CC" :D
Will apply your patch.
The other possible solution was to resort to using autotools again for png...

**Comment by Ghabry** [comment]
I see another problem :roll_eyes: zlib _always_ installs both shared and static lib and the shared lib is found first...

Fortunately others dislike this, too: https://github.com/microsoft/vcpkg/blob/master/ports/zlib/0002-build-static-or-shared-not-both.patch

**Pull request merged**
