### PR TITLE
3ds/wii/switch: Let the user take care of devkitXXX

### LINKED ISSUE #38: Support devkitPro pacman (fix buildsystem)
The devkitPro team broke the update script a few days ago which means three of our scripts are broken now -_-

### PR DESCRIPTION
**Pull request by carstene1ns**
3ds: Enable Opus support
wii: Enable optimizations

Resolves #38.

### CODE REVIEW

**Comment by carstene1ns** [comment]
ICU pls.
with old patch it complained about redefinitions of the pthread types.

with new patch (removed typedefs):
```
In file included from umutex.cpp:23:
umutex.h:375:5: error: 'pthread_mutex_t' does not name a type
     pthread_mutex_t  fMutex;
     ^~~~~~~~~~~~~~~
umutex.h:381:5: error: 'pthread_cond_t' does not name a type; did you mean 'thread_local'?
     pthread_cond_t   fCondition;
     ^~~~~~~~~~~~~~
     thread_local
umutex.h:378:31: error: 'PTHREAD_MUTEX_INITIALIZER' was not declared in this scope
 #define U_MUTEX_INITIALIZER  {PTHREAD_MUTEX_INITIALIZER}
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
umutex.cpp:31:31: note: in expansion of macro 'U_MUTEX_INITIALIZER'
 static UMutex   globalMutex = U_MUTEX_INITIALIZER;
                               ^~~~~~~~~~~~~~~~~~~
umutex.h:378:31: note: suggested alternative: 'U_MUTEX_INITIALIZER'
 #define U_MUTEX_INITIALIZER  {PTHREAD_MUTEX_INITIALIZER}
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
umutex.cpp:31:31: note: in expansion of macro 'U_MUTEX_INITIALIZER'
 static UMutex   globalMutex = U_MUTEX_INITIALIZER;
                               ^~~~~~~~~~~~~~~~~~~
*** Failed compilation command follows: ----------------------------------------------------------
ccache powerpc-eabi-g++ -I/var/lib/jenkins/workspace/toolchain-wii/wii/include -DGEKKO -D_REENTRANT -DU_HAVE_ELF_H=1 -DU_ENABLE_DYLOAD=0 -DU_HAVE_ATOMIC=1 -DU_HAVE_MMAP=0 -DU_HAVE_POPEN=0 -DU_HAVE_STRTOD_L=1 -I. -DDEFAULT_ICU_PLUGINS="/var/lib/jenkins/workspace/toolchain-wii/wii/lib/icu"  -DU_ATTRIBUTE_DEPRECATED= -DU_COMMON_IMPLEMENTATION -g0 -O2 -mcpu=750 -meabi -mhard-float -ffunction-sections --std=c++0x -c -o umutex.ao umutex.cpp
--- ( rebuild with "make VERBOSE=1 all" to show all parameters ) --------
make[1]: *** [../config/mh-unknown:49: umutex.ao] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from putil.cpp:52:
umutex.h:375:5: error: 'pthread_mutex_t' does not name a type
     pthread_mutex_t  fMutex;
     ^~~~~~~~~~~~~~~
umutex.h:381:5: error: 'pthread_cond_t' does not name a type; did you mean 'thread_local'?
     pthread_cond_t   fCondition;
     ^~~~~~~~~~~~~~
     thread_local
```

needs investigating.

**Comment by carstene1ns** [comment]
This one should be ready, just needs hardware tests on Wii, 3DS and Switch... :face_with_head_bandage:

**Comment by Ghabry** [comment]
do the jenkins build already use the new buildsystems?

Guess so because the Wii build fails due to a new type for "resetcallback"?

**Comment by carstene1ns** [comment]
Yes, this is already fixed in the Player PR.

**Comment by carstene1ns** [comment]
Wii build is currently broken, but i will test the switch build this evening.

**Comment by Ghabry** [comment]
Is worth to test with the "getcwd" workaround that Wii and Amiga already use.

**Comment by Ghabry** [comment]
The getcwd workaround works according to gbatemp but it crashes when loading a game. Only tested with Yume Nikki though which could be problematic because the filenames are not ASCII.

**Comment by carstene1ns** [comment]
Great! Time to hit the merge button here i guess.

**Comment by Ghabry** [comment]
thanks for your work. I hope this survives multiple devkitPro updates without huge extra work :/

**Pull request merged**
