### PR TITLE
Android, Wii & 3DS: And libsndfile and speexdsp. Update libpng to 1.6.23

### PR DESCRIPTION
**Pull request by Ghabry**
-

### CODE REVIEW

**Comment by Ghabry** [comment]
Confirmed working compie for 3ds, Wii and Android

**Comment by carstene1ns** [comment]
Not tested, but LGTM.

**Comment by carstene1ns** [comment]
hmm, maybe i read that wrong, but i think the additional libiconv patch seems to make the problem worse. If there is no renaming, our liblcf code needs a special handling for using the prefixed versions when building for wii.

**Comment by Ghabry** [comment]
The current situation is that liblcf will always use "iconv_open" and my patch prevents the "lib"-prefix. You mean this is something to solve in liblcf instead?

**Comment by carstene1ns** [comment]
I may still get it wrong, but to me it seems the `#define`s you disable, actually make libiconv the iconv replacement. Without them, libiconv will never be used by liblcf, only if you explicitly use `libiconv_open` and friends. Thus needing a change in liblcf for wii.

**Comment by Ghabry** [comment]
commenting out this stuff prevented the renaming for me because it is the code that defines iconv as libiconv and so on.

**Comment by carstene1ns** [comment]
btw. using speexdsp on psp results in stuttering and unresponsiveness. Hopefully this does not happen on Wii.

**Comment by Medhoc** [comment]
Wow the Android building process is reeaaally long oO.

**Comment by Medhoc** [comment]
The Android port builds and work like a charm 👍 .

**Comment by carstene1ns** [comment]
Tested and confirmed working on Wii. Do you still plan to add something or can this be merged?

The good thing is, we can still build `sndfile` and `speexdsp` for 3ds in the toolchain and not use it in official builds until the problems are resolved.

**Comment by Ghabry** [comment]
Yes, this one is ready.

**Pull request merged**
