### PR TITLE
Add fmtlib dependency

### PR DESCRIPTION
**Pull request by fmatthew5876**

### CODE REVIEW

**Comment by Ghabry** [comment]
> Do we have a way to test buildscripts for all platforms in jenkins?

Not public but I have ugly scripts that build on all platforms the libs, liblcf and Player.
I need them for my yearly library update cycle to not become insane :D

Will make a test build. Takes a few hours.

----------
Also adding "Update ICU" to my Todo list. The custom patch we have for ICU in vcpkg right now gives 404. The URL changed.

**Comment by fmatthew5876** [comment]
Ok, if you want to take this over feel free to close this and reopen your own or whatever. I have no way to test this. The changes I made were a best guess.

**Comment by Ghabry** [comment]
I meant that I have scripts to test your change. I don't have a fix for libfmt yet. Lets just hope that it compiles without much hassle ;)

Thanks for patching all the shell scripts.

**Comment by Ghabry** [comment]
Current build status:

- [ ] linux
- [ ] Android
- [x] emscripten
- [x] 3ds
- [x] Wii
- [x] Switch
- [ ] Vita

No build attempt yet:
- [ ] macOS
- [ ] (iOS)

**Comment by carstene1ns** [comment]
Icu for vcpkg should be still easier than wii and the like.

**Pull request merged**
