### PR TITLE
Update all libraries

### LINKED ISSUE #108: ICU needs Codepage 437 ibm-437_P100-1995 (MS-DOS OEM) for ZIP archives
This will be annoying because our ICUdata script only builds the most recent version so depending on the platform this must be done all again now :(

Also we do not have the old scripts for ICU59 now. Maybe is time to update ICU to the latest version ^^'.

### PR DESCRIPTION
**Pull request by Ghabry**
This updates everything everywhere.

Exceptions:
- 3DS ICU is pinned to 59.2 (lacks too many of std::thread and ::mutex)
- Wii ICU is pinned to 58.3 (you know why ;))

Fix #108 because 69.1 datafile contains Codepage 437

-----

Harfbuzz required gtkdocize, removed this dependency now...

-----

Toolchains compile, but does the Player?

- [x] Windows
- [x] Linux
- [x] macOS
- [x] Android
- [x] Emscripten
- [x] 3DS
- [x] Wii
- [x] Switch
- [x] Vita

-----

Player compiles, but does it run?

- [x] Windows
- [x] Linux
- [x] macOS
- [x] Android
- [x] Emscripten
- [x] 3DS
- [x] Wii
- [x] Switch
- [x] Vita (crashes when Audio playback starts, upstream has same problem)

### CODE REVIEW

**Comment by Ghabry** [comment]
The vita build crashes with std::system_error when entering a ICU function. So I guess compiling does not mean that std::thread and std::mutex are functional ;)

**Comment by Ghabry** [comment]
@carstene1ns could you make a test if these NROs work for you on the Switch?

https://easyrpg.org/downloads/tmp/easyrpg-nro.zip

It works in ryujinx but crashes in Yuzu so I'm unsure.

**Comment by carstene1ns** [comment]
Sure, will do this afternoon.

**Comment by carstene1ns** [comment]
Both builds appear to work. However, only tried non-japanese games, as the filesystem issue would prevent others anyway.

**Comment by Ghabry** [comment]
okay, thanks!  then I will remove the last commit as std::mutex is obviously not broken on Switch and mark this for review (the crash on Vita is nothing new :/)

**Comment by Ghabry** [comment]
frangarcj told me that vitasdk uses pthread-embedded which relies on a constructor for initialisation.
When linked statically that constructor gets removed by the linker.

Adding ``-Wl,--whole-archive -lpthread`` to the Makefile makes the crash go away, making my entire ICU patch useless. But I will keep it in the repo in case we ever need it again.

**Comment by Ghabry** [comment]
The audio thread crashing goes away by using "-O1", though this is obviously not great :/ but this means it must be a -O2 optimisation that breaks it.

**Review by fdelapena — APPROVED** [review]

**Review by carstene1ns — APPROVED** [review]
Looks good to me.

**Pull request merged**
