### PR TITLE
vcpkg: Add patched (no AVX) opus library

### PR DESCRIPTION
**Pull request by carstene1ns**
(untested)

### CODE REVIEW

**Comment by Ghabry** [comment]
At least objdump -d does not list AVX instructions anymore.
Will submit a patch to vcpkg repo, imo this is a bug in the portfile.

**Comment by carstene1ns** [comment]
Depends on whether they want to support pre-avx cpus.

**Comment by Ghabry** [comment]
Found a discussion:

https://github.com/microsoft/vcpkg/issues/8838#issuecomment-557775155

They say AVX should be opt-in via a "Feature:"

**Comment by Ghabry** [comment]
Sorry my test was wrong. Used the shared triplet and looked at the wrong file...

I try to understand there CMake file and I'm slowly kinda sure that there CMake options are broken for Windows -_-

**Comment by Ghabry** [comment]
Finally found it, AVX_SUPPORTED must be set to OFF. There are 3 vars related to AVX and thats the main one...

**Comment by Ghabry** [comment]
I submitted a patch to there repo. Is accepted but not merged
https://github.com/microsoft/vcpkg/pull/10634

**Comment by carstene1ns** [comment]
Okay, closing this when the PR is merged.

**Pull request closed without merging**
