### PR TITLE
Update pixman, better support for meson

### PR DESCRIPTION
**Pull request by carstene1ns**
Some notes:
- pixman builds flawlessly for dkpro platforms with this
- harfbuzz can be built with meson for switch, others untested. Might be a good idea to use cmake for now
- still needs cross definitions for vita, etc.
- inih builds like before, there are no platform checks

### CODE REVIEW

**Comment by Ghabry** [comment]
What appears to fix the linux build is:

```
export PKG_CONFIG=pkg-config
```

OR

Create a meson-cross.txt file with content:

```
[binaries]
pkg-config = 'pkg-config'
```

**Comment by Ghabry** [comment]
made some further tests:

Just providing

```
[binaries]
pkg-config = 'pkg-config'
```

will ignore all the env vars and just use the host compiler... bad.

I also cannot find any suggestions for a "meson-cross.txt" on the internet suitable for Android.

---

I'm really _impressed_ by meson. Great software.

**Comment by Ghabry** [comment]
I guess we really have to create this crossfile for everything ...

Edited the file to include Android:

```bash
#!/usr/bin/env bash

function flags2list() {
	while (( "$#" )); do
		echo -n "'$1'";
		[ $# -gt 1 ] && printf ",\n  " || echo ""
		shift
	done
}

function ccachify() {
	if [ "$ENABLE_CCACHE" ]; then
		echo "['ccache', `flags2list $@`]"
	else
		echo "[`flags2list $@`]"
	fi
}

# sanity
if [ -z "$1" ]; then
	echo "No platform specified." 1>&2
	exit 1
fi
ENABLE_CCACHE=$2

# defaults
PLAT_ENDIAN="little"
TOOL_PREFIX="${TARGET_HOST}-"

C=${TOOL_PREFIX}gcc
CPP={TOOL_PREFIX}g++
AR=${TOOL_PREFIX}gcc-ar
STRIP=${TOOL_PREFIX}strip

case "$1" in
"vita")
	PLAT_SYSTEM="vita"
	PLAT_CPU_FAMILY="arm"
	PLAT_CPU="cortex-a9mpcore"
	;;
"switch")
	PLAT_SYSTEM="horizon"
	PLAT_CPU_FAMILY="aarch64"
	PLAT_CPU="cortex-a57"
	;;
"3ds")
	PLAT_SYSTEM="horizon"
	PLAT_CPU_FAMILY="arm"
	PLAT_CPU="arm11mpcore"
	;;
"ogc")
	PLAT_SYSTEM="bare"
	PLAT_CPU_FAMILY="ppc"
	PLAT_CPU="ppc750"
	PLAT_ENDIAN="big"
	;;
*android*)
	PLAT_SYSTEM="android"
	case "$1" in
	armv7a*)
		PLAT_CPU_FAMILY="arm"
		;;
	aarch64*)
		PLAT_CPU_FAMILY="aarch64"
		;;
	i686*)
		PLAT_CPU_FAMILY="x86"
		;;
	x86_64*)
		PLAT_CPU_FAMILY="x86_64"
		;;
	esac
	C="clang -target $1"
	CPP="clang++ -target $1"
	AR="llvm-ar"
	STRIP="llvm-strip"
	;;
*)
	echo "Unsupported platform $1." 1>&2
	exit 1
	;;
esac

cat << EOF
# autogenerated, do not edit

[binaries]
c = ` ccachify ${C} `
cpp = ` ccachify ${CPP} `
ar = '${AR}'
strip = '${STRIP}'
pkg-config = 'pkg-config'

[built-in options]
c_args = [` flags2list $CPPFLAGS $CFLAGS `]
c_link_args = [` flags2list $LDFLAGS $LIBS `]
cpp_args = [` flags2list $CPPFLAGS $CXXFLAGS `]
cpp_link_args = [` flags2list $LDFLAGS $LIBS `]

[host_machine]
system = '${PLAT_SYSTEM}'
cpu_family = '${PLAT_CPU_FAMILY}'
cpu = '${PLAT_CPU}'
endian = '${PLAT_ENDIAN}'
EOF
```

```patch
diff --git a/android/2_build_toolchain.sh b/android/2_build_toolchain.sh
index b5ff50a..d313487 100755
--- a/android/2_build_toolchain.sh
+++ b/android/2_build_toolchain.sh
@@ -97,15 +97,19 @@ function build() {
 	export TARGET_HOST="$4"
 	export CC="clang -target ${TARGET_HOST}${TARGET_API}"
 	export CXX="clang++ -target ${TARGET_HOST}${TARGET_API}"
+
 	if [ "$ENABLE_CCACHE" ]; then
 		export CC="ccache $CC"
 		export CXX="ccache $CXX"
 	fi
 
+	mkdir -p $PLATFORM_PREFIX
+	$SCRIPT_DIR/../shared/mk-meson-cross.sh "${TARGET_HOST}${TARGET_API}" "$ENABLE_CCACHE" > $PLATFORM_PREFIX/meson-cross.txt
+
 	install_lib_zlib
 	install_lib $LIBPNG_DIR $LIBPNG_ARGS
 	install_lib_cmake $FREETYPE_DIR $FREETYPE_ARGS -DFT_DISABLE_HARFBUZZ=ON
-	install_lib_cmake $HARFBUZZ_DIR $HARFBUZZ_ARGS_CMAKE
+	install_lib_meson $HARFBUZZ_DIR $HARFBUZZ_ARGS
 	install_lib_cmake $FREETYPE_DIR $FREETYPE_ARGS -DFT_DISABLE_HARFBUZZ=OFF
 	install_lib_meson $PIXMAN_DIR $PIXMAN_ARGS
 	install_lib_cmake $EXPAT_DIR $EXPAT_ARGS
```

**Comment by carstene1ns** [comment]
emscripten build of harfbuzz picks up host libraries, which is interesting because `EM_PKG_CONFIG_PATH` should prevent this...

**Comment by Ghabry** [comment]
Looks like ``EM_PKG_CONFIG_PATH`` is handled by ``emconfigure``/``emcmake`` to inject an environment (overrides ``PKG_CONFIG_LIBDIR`` etc.) so what appears to work is:

```patch
diff --git a/shared/common.sh b/shared/common.sh
index d7255a0..cfba1cb 100644
--- a/shared/common.sh
+++ b/shared/common.sh
@@ -149,7 +149,7 @@ function install_lib_meson {
 
 		rm -rf build
 
-		meson setup build --prefix $PLATFORM_PREFIX --buildtype=plain \
+		$CONFIGURE_WRAPPER meson setup build --prefix $PLATFORM_PREFIX --buildtype=plain \
 			-Ddefault_library=static --cross-file $MESON_CROSS $@
 		meson compile -C build
 		meson install -C build
```

btw there is a meson-cross.txt already versioned for emscripten. That one can be deleted.

**Comment by Ghabry** [comment]
To convince emscripten to not find the system glib storing the pkgconfig libdir in the meson.txt file appears to work:

```patch
diff --git a/shared/mk-meson-cross.sh b/shared/mk-meson-cross.sh
index 4ad04b0..696c02c 100755
--- a/shared/mk-meson-cross.sh
+++ b/shared/mk-meson-cross.sh
@@ -129,4 +129,7 @@ system = '${PLAT_SYSTEM}'
 cpu_family = '${PLAT_CPU_FAMILY}'
 cpu = '${PLAT_CPU}'
 endian = '${PLAT_ENDIAN}'
+
+[properties]
+pkg_config_libdir = [ ` array2list ${PKG_CONFIG_LIBDIR//:/" "} ` ]
 EOF
```

But I'm honestly not sure if this is even the correct way to specify it. The documentation says ``list of path`` without an example what a list of paths it, so my guess is an array of paths like we already do for the compiler args.

**Comment by carstene1ns** [comment]
Wanted to switch after building. But it is kinda dumb that you cannot change draft status from their mobile app.

**Review by Ghabry — APPROVED** [review]

**Pull request merged**
