### PR TITLE
[Android] Get back to Android SDK 23

### PR DESCRIPTION
**Pull request by BlisterB**
I'm not able to test this PR (poor internet connection) but it should be well :).

### CODE REVIEW

**Comment by Ghabry** [comment]
For the SDK download you can probably use the latest URL you can find but this is Google so wouldn't bet on this :/

**Comment by Ghabry** [comment]
@BlisterB 
ping? :)

**Comment by BlisterB** [comment]
Hi Ghabry :), sorry for the delay. You are absolutely right, sorry for the confusion between Android SDK and Target API, I've got my "real" internet connection back so I'll fix and test the thing as soon as possible :).

**Comment by Ghabry** [comment]
@BlisterB 
No problem there is still ~1 week left before 0.5.1 release.

**Comment by BlisterB** [comment]
That should be better, I'm building everything and I will do a git rebase interactive if the result is ok.

**Comment by BlisterB** [comment]
Little problem : the link for icudata leads to a 404 error :/
https://easy-rpg.org/jenkins/job/icudata/lastSuccessfulBuild/artifact/icu/source/data/out/icudata.tar.gz

**Comment by carstene1ns** [comment]
Replace it with `https://easyrpg.org/downloads/tmp/icudata56.tar.gz` for now.

**Comment by BlisterB** [comment]
Okay.
Brace yourself, the MacOS nightmare starts again, ./2_build_toolchain.sh fails on my mac with this : 

`
patching libraries
patching file android-ndk-r10e/sources/android/cpufeatures/cpu-features.c
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
glibtoolize: and rerunning glibtoolize and aclocal.
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:73: installing './compile'
configure.ac:62: installing './missing'
demos/Makefile.am:11: warning: source file '../test/utils.c' is in a subdirectory,
demos/Makefile.am:11: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
demos/Makefile.am:11: warning: source file '../test/utils-prng.c' is in a subdirectory,
demos/Makefile.am:11: but option 'subdir-objects' is disabled
demos/Makefile.am: installing './depcomp'
patching file config.sub
patching file src/common.h
patching file src/load.c
patching file src/load_helpers.c
patching file android.c
patching file timidity.c
patching file acinclude/libtool.m4
patching file Makefile.in
Generating build information using autoconf
This may take a while ...
configure.in:30: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2670: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2680: AC_LINK_IFELSE is expanded from...
aclocal.m4:1040: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal.m4:5237: _LT_LINKER_SHLIBS is expanded from...
aclocal.m4:5322: _LT_LANG_C_CONFIG is expanded from...
aclocal.m4:252: _LT_SETUP is expanded from...
aclocal.m4:101: LT_INIT is expanded from...
configure.in:30: the top level
configure.in:30: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2670: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2680: AC_LINK_IFELSE is expanded from...
aclocal.m4:5237: _LT_LINKER_SHLIBS is expanded from...
aclocal.m4:5322: _LT_LANG_C_CONFIG is expanded from...
aclocal.m4:252: _LT_SETUP is expanded from...
aclocal.m4:101: LT_INIT is expanded from...
configure.in:30: the top level
Now you are ready to run ./configure
preparing ICU host build
sed: 1: "tools/toolutil/pkg_genc.h": undefined label 'ools/toolutil/pkg_genc.h'
`

**Comment by fdelapena** [comment]
> undefined label 'ools/toolutil/pkg_genc.h'

This seems to be a possible issue (ools)

**Comment by Ghabry** [comment]
That sed-line does use "-i" instead of "-i.bak", maybe that fixes it.

**Comment by Ghabry** [comment]
probably same issue as here: https://github.com/EasyRPG/Player/issues/1042#issuecomment-253867490

**Comment by BlisterB** [comment]
Oh guys, it worked :).
Does the mac os fix is compatible with Linux ?

**Comment by carstene1ns** [comment]
Yes.

**Comment by Ghabry** [comment]
I would Say this can be squashed into 1 commit

**Comment by BlisterB** [comment]
It should be better that way :).

**Pull request merged**
