### PR TITLE
Android : git pull in liblcf folder before building

### PR DESCRIPTION
**Pull request by Medhoc**
This git pull is usefull if the script is not executed for the first time (in case of modification).

### CODE REVIEW

**Comment by carstene1ns** [comment]
What about cloning and pulling only when necessary:

```bash
if [ -d liblcf/.git ]; then
  git -C liblcf pull
else
  git clone https://github.com/EasyRPG/liblcf.git
fi
cd liblcf
```

**Comment by Medhoc** [comment]
This is indeed a more elegant way to do it :).

**Comment by Medhoc** [comment]
Ah, I was doing the same thing for the Player directory xp.

**Comment by carstene1ns** [comment]
Oh, sorry. You need to open another pull request then. :v:

**Pull request merged**
