### PR TITLE
Feature: automatic library updates

### PR DESCRIPTION
**Pull request by carstene1ns**
### This is actually 2 changes at once:
- ini for library definitions, makes scripting easier
- updater script using anitya, automatically run by github actions every week

### Some nice features:
- Uses a supercharged ini format with replacements
- adding libraries to/updating `packages.sh` is easier
- no more missed library updates
  - will open a pull request for each bunch, can stay open until issues are resolved
  - parallel updates (in other PRs) will be recognized once applied
- no functional change for existing scripts

### Whats missing:
- Automated PR builders on jenkins, to find breakage

### Here is an example of such pull request:
https://github.com/carstene1ns/easyrpg-buildscripts/pull/2
(I have pushed an update to harfbuzz and freetype to master branch, these have been removed)
2023-11-10T04:13:39,358750502+01:00

### CODE REVIEW

**Review by fdelapena — APPROVED** [review]

**Comment by carstene1ns** [comment]
jenkins: test this please <3

**Comment by Ghabry** [comment]
Thanks for the script and automation. This will save lots of time in maintaining the libs.

Is there special handling for ICU? (E.g. Pinned to 69.1) updates to ICU are always quite hard because they library is so huge. New data file etc.

Everything else can be on latest as is usually frustration free ;)

**Comment by carstene1ns** [comment]
There is currently no special path for ICU, as well as custom platform libraries (i.e. mostly old icu). The CI/CD should notify us when there is action necessary. So IMO not worth to have special handling right now.

Most of the time one or two libraries need updates, so the changes are manageable. Currently there are 9 updates pending, which will likely break.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Review by Ghabry — APPROVED** [review]
Thanks! This is great to make library updates less annoying.

Added the other PR builders (except Windows obviously).

Linux build error is just lack of meson :sweat_smile: . Is now installed. Will not rerun this.

Android will only build ARMv7/arm64 so it doesn't take ages to build when the cache is cold (time will tell if this is enough :))

**Pull request merged**
