### PR TITLE
Vcpkg:  Add Freetype[core]. Prevents the build of bzip2.

### PR DESCRIPTION
**Pull request by Ghabry**
Freetype learned feature selection a while ago, so we can get rid of bzip2 :)

### CODE REVIEW

**Comment by Ghabry** [comment]
Freetype[core] is enough to build harfbuzz[ucdn] but the depedency resolution has a bug and still installs bzip2 when you install both at once :/

I filed a bug here: https://github.com/microsoft/vcpkg/issues/10678

**Comment by carstene1ns** [comment]
Can we work around this when we do the install in 2 steps (seperate `install` lines)?

**Comment by Ghabry** [comment]
Yes this is what I used for the testing (and why I didn't notice this but)

**Comment by Ghabry** [comment]
nope, specifying freetype twice doesn't help. Is always ignored.

No idea how this can't be a bug (or they just don't understand what I want -_-) but okay.....

1.

```
> vcpkg.exe --triplet x86-windows install freetype[core] harfbuzz[core,ucdn]
Computing installation plan...
The following packages will be built and installed:
  * bzip2[core]:x86-windows
    freetype[bzip2,core,png]:x86-windows
    harfbuzz[core,ucdn]:x86-windows
  * libpng[core]:x86-windows
  * ragel[core]:x86-windows
  * zlib[core]:x86-windows

> vcpkg list
bzip2:x86-windows                                  1.0.6-5
freetype:x86-windows                               2.10.1-6
freetype[bzip2]:x86-windows
freetype[png]:x86-windows
harfbuzz:x86-windows                               2.5.3
harfbuzz[ucdn]:x86-windows 
libpng:x86-windows                                 1.6.37-7
ragel:x86-windows                                  6.10-3
zlib:x86-windows                                   1.2.11-6
```

2.

```
> vcpkg.exe --triplet x86-windows install freetype[core]
Computing installation plan...
The following packages will be built and installed:
    freetype[core]:x86-windows
  * zlib[core]:x86-windows
  
> vcpkg.exe --triplet x86-windows install harfbuzz[core,ucdn]
Computing installation plan...
The following packages will be built and installed:
    harfbuzz[core,ucdn]:x86-windows
  * ragel[core]:x86-windows

> vcpkg list
freetype:x86-windows                               2.10.1-6
harfbuzz:x86-windows                               2.5.3
harfbuzz[ucdn]:x86-windows
ragel:x86-windows                                  6.10-3
zlib:x86-windows                                   1.2.11-6
```

**Comment by Ghabry** [comment]
The bug I reported is actually a different bug in the dependency resolution. When they fix it it will always install bzip2 and libpng.

The actual bug is a problem with the harfbuzz portfile. See my last comment here. Will submit a patch.

https://github.com/microsoft/vcpkg/issues/10678#issuecomment-621253257

**Comment by Ghabry** [comment]
My patch to harfbuzz was just merged, so this PR will work as expected now.

**Pull request merged**
