### PR TITLE
Add 3DS and Wii Toolchain scripts

### PR DESCRIPTION
**Pull request by Ghabry**
-

### CODE REVIEW

**Comment by Ghabry** [comment]
Okay, build fails for me >.<. Needs a fix somewhere. E.g. ctrulib must be installed before mpg123 because we need socket.h :D

**Comment by carstene1ns** [comment]
btw. sdl-wii is too old to support external modplug and only uses internal mikmod.
also the internal timidity got some good patches, but also missing from sdl-wii yet.

**Comment by Ghabry** [comment]
hmm, have to check if I can patch the SDL-Wii code (repo is an ugly mess) in a SDL1.2 hg

**Comment by carstene1ns** [comment]
well, instead of ugly patching it here, this can be done correctly and proposed for inclusion in the official repo.

**Comment by carstene1ns** [comment]
LGTM, merging.

**Pull request merged**
